### ISSUE TITLE
Previous state thing caused crash

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#36]
### Spark link

N/A

### Stack trace

```
java.lang.IllegalStateException: Previous state should be 0, not 3
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:683)
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:315)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1967)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1749)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1443)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Canvas version

Current Purpur Version: 1.21-DEV-0bfcfed (MC: 1.21)*
* You are running the latest version
Previous: 1.21-2259-b3709b1 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
fixed

**Comment by TheDeafCreeper** [comment]
[crash-2024-07-12_16.10.48-server.txt](https://github.com/user-attachments/files/16199299/crash-2024-07-12_16.10.48-server.txt)

Not fixed (I cant reopen this)

**Comment by Dueris** [comment]
is this when unlocking the tickloop?

**Comment by TheDeafCreeper** [comment]
no I just had 50 bots existing around the place

**Comment by Dueris** [comment]
k

**Comment by Dueris** [comment]
fixed - fr this time
